### ISSUE TITLE
Setup quality checking workflow for repository

### ISSUE THREAD

**Issue by TranAnhVu0411** [FEvalTool/Evaluation-Tool-Backend#1]
### Description
Recognizing the significance of unit testing and code coverage is essential to ensuring that all code pushed and merged into the main branch maintains high quality, free from bugs and defects. Consequently, this initiative aims to establish a workflow to automatically execute tests and assess code coverage through GitHub Actions and SonarCloud.

### Resource
- [Efficient GitHub Code Scanning with SonarCloud and GitHub Actions | SonarQube | GitHub | Code Scan](https://www.youtube.com/watch?v=AYUaIiWZ-_w) (You can follow the first beginning part of this tutorial to understand most of the github, sonar cloud and how to retrieve token from both of them. However, the later part will be failed since the project in sonar cloud is not automatically created when Github Action workflow is in process)
- [How to Connect Your GitHub Project to Sonar](https://dev.to/olsido/how-to-connect-your-github-project-to-sonar-9ic) (Better documentation, great explanation to follow)

### Tasks
- [x] Investigate the process
- [x] Implement the process on Github and Sonar Cloud
- [x] Testing the implementation
- [x] Fix minor error
