### ISSUE TITLE
Setup template for issue, PR and Wiki and Create Branch/Commit format

### ISSUE THREAD

**Issue by TranAnhVu0411** [FEvalTool/Evaluation-Tool-Backend#4]
### Description
To ensure effective organization, it is essential to establish standardized templates for issues, pull requests, and the Wiki. Additionally, we will include documentation on the Wiki to assist new contributors in creating branches and committing in the appropriate format.

### Resource
- [Configuring issue templates for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
- [Creating a pull request template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

### Tasks
- [x] Setup template for PR
- [x] Setup template for issue
- [ ] ~~Setup template for wiki~~ (Move to [Evaluation-Tool-Wiki](https://github.com/FEvalTool/Evaluation-Tool-Wiki) repo)
- [ ] ~~Write documentation for Branch/Commit format structure~~ (Move to [Evaluation-Tool-Wiki](https://github.com/FEvalTool/Evaluation-Tool-Wiki) repo)
