### ISSUE TITLE
Setup project and Users application

### ISSUE THREAD

**Issue by TranAnhVu0411** [FEvalTool/Evaluation-Tool-Backend#6]
### Description
We are going to set up the project and Users application, and in Users application, we are going to set up Models base on ERD mention in wiki 

### Resource
None

### Tasks
(Tasks list to execute this issue - **Required**)
- [ ] Set up project
- [ ] Set up user application
- [ ] Set up user related models

### Note
This may fail the sonar scan since there is no test in this case, we will try to figure a solution to bypass this
